global:
  scrape_interval: 15s # Default is every 15 seconds.
  evaluation_interval: 15s # Default is every 15 seconds.

rule_files:
  - "/home/swati_nema@acds.net.in/Desktop/ALL_TERRAFROM/Iauro_Assignment/FinalAssignment/CRUD_PromClient/alerts_rules.yml"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['localhost:3101']